### ISSUE TITLE
Can't get it to write to Supabase postgresql database

### ISSUE THREAD

**Issue by mzavattaro** [leandroercoli/SaasterKit#2]
Struggling to get it to write to my Supabase postgresql database. I get the following error after I sign in via Clerk and navigate to the `/dashboard`:

<img width="743" alt="Screenshot 2024-05-26 at 1 08 59 PM" src="https://github.com/leandroercoli/SaasterKit/assets/22721781/be7ca52d-6d4e-43ef-a3b6-eea6c8c10897">

I've followed the instructions and can confirm that Clerk is setup correctly because it registers new users and when they log in within the Clerk dashboard.

Supabase establishes the tables within the dashboard correctly and can see them in the Supabase database dashboard. Migrations are in symc.

Looking in Prisma Studio, it correctly builds the tables but they're all empty.
I still can't seem to get it to write to the database.

My `.env` file looks like this:
```
SUPABASE_DATABASE_URL=
SUPABASE_DIRECT_URL=

CLERK_SECRET_KEY=

LEMONSQUEEZY_API_KEY=
LEMONSQUEEZY_STORE_ID=
LEMONSQUEEZY_WEBHOOK_SECRET=

RESEND_API_KEY=

SENTRY_DSN=
SENTRY_ORG=
SENTRY_PROJECT=

```
My `.env.local` file looks like this:
```
# Used to check if the signed in user is the author of this project (for admin features)
NEXT_PUBLIC_AUTHOR_EMAIL=

# Clerk
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=

#Google Analytics
NEXT_PUBLIC_MEASUREMENT_ID=
```
Both are in the projects root.

Any help would be appreciated!

**Comment by leandroercoli** [comment]
Hey @mzavattaro ! You're saying you can see new users on Clerk but not on Supabase right? Have you checked if you set up Clerk's webhook correctly? Make sure you're using a tool like `localtunnel` to expose your local environment to the internet, otherwise it won't be reachable by Clerk and you won't receive the `user.created` events. Check out the official docs here: https://clerk.com/blog/webhooks-getting-started

**Comment by mzavattaro** [comment]
That's correct, I can see new users and sessions in Clerk but not Supabase.
I'm using Ngrok to create a public URL for the Clerk Webhook and as far as testing goes, it does succeed and I can console.log the `evt. data` to see the object coming from the Clerk Webhook which is good. But it doesn't create the user in the database because you can see in the terminal logs that `user` is always null thereby throwing that error in the OP.

<img width="348" alt="Screenshot 2024-05-27 at 8 32 14 AM" src="https://github.com/leandroercoli/SaasterKit/assets/22721781/d9a59776-8689-4c63-a299-c4e75b0900da">

**Comment by mzavattaro** [comment]
Update: I think I got it working by completing purging Clerk users and Supabase. May have been some mismatch of IDs during the initial init when setting up the project whereby the user did exist in Clerk but didn't exist in the database. So signing in Clerk was saying this user exists, but as far as the database was concerned, that user didn't exist so they were clashing.

I wonder if it's worth having some sort check to see if the Clerk user already exists but they don't exist in the database, when they try to sign in, add them to the database. As some sort of rare edge case fallback?

**Comment by leandroercoli** [comment]
I see. Yeah, maybe you also need to capture the `user.update` event. I guess if you had already signed up with that user, then it won't send the `user.created` event. 

As a fallback, I think you could add some extra code on the `getSignedInUser` function, to create the user if they're signed up on Clerk, but not found in the database.
